In [1]:
import pandas as pd

# 1. Website Sessions

### Import File

In [2]:
ws = pd.read_csv("D:/PROJECTS/Maven+Fuzzy+Factory(E-Commerce)/website_sessions.csv")
ws.head(5)

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,19-03-2012 08:04,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,19-03-2012 08:16,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,19-03-2012 08:26,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
3,4,19-03-2012 08:37,4,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
4,5,19-03-2012 09:00,5,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com

In [3]:
ws.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472871 entries, 0 to 472870
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   website_session_id  472871 non-null  int64
 1   created_at          472871 non-null  object
 2   user_id             472871 non-null  int64
 3   is_repeat_session   472871 non-null  int64
 4   utm_source          389543 non-null  object
 5   utm_campaign        389543 non-null  object
 6   utm_content         389543 non-null  object
 7   device_type         472871 non-null  object
 8   http_referer        432954 non-null  object
dtypes: int64(3), object(6)
memory usage: 32.5+ MB

### Changing datatype of created_at from object to datetime

In [4]:
ws["created_at"] = pd.to_datetime(ws["created_at"], dayfirst = True)

In [5]:
ws.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472871 entries, 0 to 472870
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   website_session_id  472871 non-null  int64
 1   created_at          472871 non-null  datetime64[ns]
 2   user_id             472871 non-null  int64
 3   is_repeat_session   472871 non-null  int64
 4   utm_source          389543 non-null  object
 5   utm_campaign        389543 non-null  object
 6   utm_content         389543 non-null  object
 7   device_type         472871 non-null  object
 8   http_referer        432954 non-null  object
dtypes: datetime64[ns](1), int64(3), object(5)
memory usage: 32.5+ MB

### Changing datatype of is_repeat_session from int64 to boolean

In [6]:
ws["is_repeat_session"] = ws["is_repeat_session"].astype("bool")
ws.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472871 entries, 0 to 472870
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   website_session_id  472871 non-null  int64
 1   created_at          472871 non-null  datetime64[ns]
 2   user_id             472871 non-null  int64
 3   is_repeat_session   472871 non-null  bool
 4   utm_source          389543 non-null  object
 5   utm_campaign        389543 non-null  object
 6   utm_content         389543 non-null  object
 7   device_type         472871 non-null  object
 8   http_referer        432954 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(2), object(5)
memory usage: 29.3+ MB

In [7]:
ws["website_session_id"].duplicated().sum()

np.int64(0)

In [8]:
ws.isnull().sum()

website_session_id        0
created_at                0
user_id                   0
is_repeat_session         0
utm_source            83328
utm_campaign          83328
utm_content           83328
device_type               0
http_referer          39917
dtype: int64

### Filling NULL values with appropriate values

In [9]:
ws["utm_source"] = ws["utm_source"].fillna("direct") 
ws["utm_campaign"] = ws["utm_campaign"].fillna("none")
ws["utm_content"] = ws["utm_content"].fillna("none")
ws["http_referer"] = ws["http_referer"].fillna("direct")
ws.isnull().sum()

website_session_id    0
created_at            0
user_id               0
is_repeat_session     0
utm_source            0
utm_campaign          0
utm_content           0
device_type           0
http_referer          0
dtype: int64

In [10]:
ws

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 08:04:00,1,False,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,2012-03-19 08:16:00,2,False,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 08:26:00,3,False,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
3,4,2012-03-19 08:37:00,4,False,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
4,5,2012-03-19 09:00:00,5,False,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
...,...,...,...,...,...,...,...,...,...
472866,472867,2015-03-19 07:49:00,394314,False,gsearch,brand,g_ad_2,desktop,https://www.gsearch.com
472867,472868,2015-03-19 07:54:00,394315,False,bsearch,nonbrand,b_ad_1,mobile,https://www.bsearch.com
472868,472869,2015-03-19 07:55:00,394316,False,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
472869,472870,2015-03-19 07:56:00,394317,False,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
472870,472871,2015-03-19 07:59:00,394318,False,direct,none,none,mobile,direct

### Adding year and month, month name column

In [11]:
ws.insert(2, "year", ws["created_at"].dt.year)
ws.insert(3, "month", ws["created_at"].dt.month)
ws.insert(4, "month_name", ws["created_at"].dt.month_name())
ws

,website_session_id,created_at,year,month,month_name,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 08:04:00,2012,3,March,1,False,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,2012-03-19 08:16:00,2012,3,March,2,False,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 08:26:00,2012,3,March,3,False,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
3,4,2012-03-19 08:37:00,2012,3,March,4,False,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
4,5,2012-03-19 09:00:00,2012,3,March,5,False,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
...,...,...,...,...,...,...,...,...,...,...,...,...
472866,472867,2015-03-19 07:49:00,2015,3,March,394314,False,gsearch,brand,g_ad_2,desktop,https://www.gsearch.com
472867,472868,2015-03-19 07:54:00,2015,3,March,394315,False,bsearch,nonbrand,b_ad_1,mobile,https://www.bsearch.com
472868,472869,2015-03-19 07:55:00,2015,3,March,394316,False,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
472869,472870,2015-03-19 07:56:00,2015,3,March,394317,False,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
472870,472871,2015-03-19 07:59:00,2015,3,March,394318,False,direct,none,none,mobile,direct

### Exporting Dataset

In [85]:
ws.to_csv("website_sessions_cleaned.csv", index=False)

# 2. Website Pageviews

In [86]:
wp = pd.read_csv("D:/PROJECTS/Maven+Fuzzy+Factory(E-Commerce)/website_pageviews.csv")
wp

,website_pageview_id,created_at,website_session_id,pageview_url
0,1,19-03-2012 08:04,1,/home
1,2,19-03-2012 08:16,2,/home
2,3,19-03-2012 08:26,3,/home
3,4,19-03-2012 08:37,4,/home
4,5,19-03-2012 09:00,5,/home
...,...,...,...,...
1048570,1048571,16-01-2015 18:59,421952,/the-birthday-sugar-panda
1048571,1048572,16-01-2015 19:01,421954,/products
1048572,1048573,16-01-2015 19:03,421952,/cart
1048573,1048574,16-01-2015 19:03,421956,/home
1048574,1048575,16-01-2015 19:03,421952,/shipping

In [87]:
wp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 4 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   website_pageview_id  1048575 non-null  int64
 1   created_at           1048575 non-null  object
 2   website_session_id   1048575 non-null  int64
 3   pageview_url         1048575 non-null  object
dtypes: int64(2), object(2)
memory usage: 32.0+ MB

# Changing datatype of created_at from object to datetime

In [88]:
wp["created_at"] = pd.to_datetime(wp["created_at"], dayfirst = True)
wp.info()
wp.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 4 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   website_pageview_id  1048575 non-null  int64
 1   created_at           1048575 non-null  datetime64[ns]
 2   website_session_id   1048575 non-null  int64
 3   pageview_url         1048575 non-null  object
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 32.0+ MB

   website_pageview_id          created_at  website_session_id pageview_url
0                    1 2012-03-19 08:04:00                   1        /home
1                    2 2012-03-19 08:16:00                   2        /home
2                    3 2012-03-19 08:26:00                   3        /home
3                    4 2012-03-19 08:37:00                   4        /home
4                    5 2012-03-19 09:00:00                   5        /home

In [89]:
wp["website_pageview_id"].duplicated().sum()

np.int64(0)

In [90]:
wp.isnull().sum()

website_pageview_id    0
created_at             0
website_session_id     0
pageview_url           0
dtype: int64

### Adding year, month, month name column

In [91]:
wp.insert(2,"year",wp["created_at"].dt.year)
wp.insert(3,"month",wp["created_at"].dt.month)
wp.insert(4,"month_name",wp["created_at"].dt.month_name())
wp

,website_pageview_id,created_at,year,month,month_name,website_session_id,pageview_url
0,1,2012-03-19 08:04:00,2012,3,March,1,/home
1,2,2012-03-19 08:16:00,2012,3,March,2,/home
2,3,2012-03-19 08:26:00,2012,3,March,3,/home
3,4,2012-03-19 08:37:00,2012,3,March,4,/home
4,5,2012-03-19 09:00:00,2012,3,March,5,/home
...,...,...,...,...,...,...,...
1048570,1048571,2015-01-16 18:59:00,2015,1,January,421952,/the-birthday-sugar-panda
1048571,1048572,2015-01-16 19:01:00,2015,1,January,421954,/products
1048572,1048573,2015-01-16 19:03:00,2015,1,January,421952,/cart
1048573,1048574,2015-01-16 19:03:00,2015,1,January,421956,/home
1048574,1048575,2015-01-16 19:03:00,2015,1,January,421952,/shipping

### Exporting Dataset

In [92]:
wp.to_csv("website_pageviews_cleaned.csv", index = False)

# 3. Products

In [93]:
pr = pd.read_csv("D:/PROJECTS/Maven+Fuzzy+Factory(E-Commerce)/products.csv")
pr

   product_id        created_at                product_name
0           1  19-03-2012 08:00      The Original Mr. Fuzzy
1           2  06-01-2013 13:00       The Forever Love Bear
2           3  12-12-2013 09:00    The Birthday Sugar Panda
3           4  05-02-2014 10:00  The Hudson River Mini bear

In [94]:
pr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    4 non-null      int64
 1   created_at    4 non-null      object
 2   product_name  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

### Changing datatype of created_at from object to datetime

In [95]:
pr["created_at"] = pd.to_datetime(pr["created_at"], dayfirst = True)
pr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    4 non-null      int64
 1   created_at    4 non-null      datetime64[ns]
 2   product_name  4 non-null      object
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 228.0+ bytes

### Adding year, month, month name columns

In [96]:
pr.insert(2,"year",pr["created_at"].dt.year)
pr.insert(3,"month",pr["created_at"].dt.month)
pr.insert(4,"month_name",pr["created_at"].dt.month_name())
pr

,product_id,created_at,year,month,month_name,product_name
0,1,2012-03-19 08:00:00,2012,3,March,The Original Mr. Fuzzy
1,2,2013-01-06 13:00:00,2013,1,January,The Forever Love Bear
2,3,2013-12-12 09:00:00,2013,12,December,The Birthday Sugar Panda
3,4,2014-02-05 10:00:00,2014,2,February,The Hudson River Mini bear

### Exporting dataset

In [97]:
pr.to_csv("products_cleaned.csv", index = False)

# 4. Orders

In [98]:
od = pd.read_csv("D:/PROJECTS/Maven+Fuzzy+Factory(E-Commerce)/orders.csv")
od

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,19-03-2012 10:42,20,20,1,1,49.99,19.49
1,2,19-03-2012 19:27,104,104,1,1,49.99,19.49
2,3,20-03-2012 06:44,147,147,1,1,49.99,19.49
3,4,20-03-2012 09:41,160,160,1,1,49.99,19.49
4,5,20-03-2012 11:28,177,177,1,1,49.99,19.49
...,...,...,...,...,...,...,...,...
32308,32309,19-03-2015 03:58,472795,394255,1,1,49.99,19.49
32309,32310,19-03-2015 04:10,472798,394257,4,1,29.99,9.49
32310,32311,19-03-2015 05:27,472809,394268,2,2,89.98,31.98
32311,32312,19-03-2015 05:35,472814,394273,4,1,29.99,9.49
32312,32313,19-03-2015 05:38,472818,386000,1,1,49.99,19.49

In [99]:
od.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32313 entries, 0 to 32312
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            32313 non-null  int64
 1   created_at          32313 non-null  object
 2   website_session_id  32313 non-null  int64
 3   user_id             32313 non-null  int64
 4   primary_product_id  32313 non-null  int64
 5   items_purchased     32313 non-null  int64
 6   price_usd           32313 non-null  float64
 7   cogs_usd            32313 non-null  float64
dtypes: float64(2), int64(5), object(1)
memory usage: 2.0+ MB

### Changing datatype of created_at from object to datatime

In [100]:
od["created_at"] = pd.to_datetime(od["created_at"], dayfirst = True)
od.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32313 entries, 0 to 32312
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            32313 non-null  int64
 1   created_at          32313 non-null  datetime64[ns]
 2   website_session_id  32313 non-null  int64
 3   user_id             32313 non-null  int64
 4   primary_product_id  32313 non-null  int64
 5   items_purchased     32313 non-null  int64
 6   price_usd           32313 non-null  float64
 7   cogs_usd            32313 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(5)
memory usage: 2.0 MB

In [101]:
od.duplicated().sum()

np.int64(0)

In [102]:
od.isnull().sum()

order_id              0
created_at            0
website_session_id    0
user_id               0
primary_product_id    0
items_purchased       0
price_usd             0
cogs_usd              0
dtype: int64

In [103]:
od[["price_usd", "cogs_usd"]].describe()

          price_usd      cogs_usd
count  32313.000000  32313.000000
mean      59.991636     22.355406
std       17.808771      6.238621
min       29.990000      9.490000
25%       49.990000     19.490000
50%       49.990000     19.490000
75%       59.990000     22.490000
max      109.980000     41.980000

### Adding year, month. month name columns

In [104]:
od.insert(2,"year",od["created_at"].dt.year)
od.insert(3,"month",od["created_at"].dt.month)
od.insert(4,"month_name",od["created_at"].dt.month_name())
od

,order_id,created_at,year,month,month_name,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,2012-03-19 10:42:00,2012,3,March,20,20,1,1,49.99,19.49
1,2,2012-03-19 19:27:00,2012,3,March,104,104,1,1,49.99,19.49
2,3,2012-03-20 06:44:00,2012,3,March,147,147,1,1,49.99,19.49
3,4,2012-03-20 09:41:00,2012,3,March,160,160,1,1,49.99,19.49
4,5,2012-03-20 11:28:00,2012,3,March,177,177,1,1,49.99,19.49
...,...,...,...,...,...,...,...,...,...,...,...
32308,32309,2015-03-19 03:58:00,2015,3,March,472795,394255,1,1,49.99,19.49
32309,32310,2015-03-19 04:10:00,2015,3,March,472798,394257,4,1,29.99,9.49
32310,32311,2015-03-19 05:27:00,2015,3,March,472809,394268,2,2,89.98,31.98
32311,32312,2015-03-19 05:35:00,2015,3,March,472814,394273,4,1,29.99,9.49
32312,32313,2015-03-19 05:38:00,2015,3,March,472818,386000,1,1,49.99,19.49

### Exporting dataset

In [105]:
od.to_csv("orders_cleaned.csv", index = False)

# 5. Order Items

In [106]:
oi = pd.read_csv("D:/PROJECTS/Maven+Fuzzy+Factory(E-Commerce)/order_items.csv")
oi

,order_item_id,created_at,order_id,product_id,is_primary_item,price_usd,cogs_usd
0,1,19-03-2012 10:42,1,1,1,49.99,19.49
1,2,19-03-2012 19:27,2,1,1,49.99,19.49
2,3,20-03-2012 06:44,3,1,1,49.99,19.49
3,4,20-03-2012 09:41,4,1,1,49.99,19.49
4,5,20-03-2012 11:28,5,1,1,49.99,19.49
...,...,...,...,...,...,...,...
40020,40021,19-03-2015 04:10,32310,4,1,29.99,9.49
40021,40022,19-03-2015 05:27,32311,2,1,59.99,22.49
40022,40023,19-03-2015 05:27,32311,4,0,29.99,9.49
40023,40024,19-03-2015 05:35,32312,4,1,29.99,9.49
40024,40025,19-03-2015 05:38,32313,1,1,49.99,19.49

In [107]:
oi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40025 entries, 0 to 40024
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    40025 non-null  int64
 1   created_at       40025 non-null  object
 2   order_id         40025 non-null  int64
 3   product_id       40025 non-null  int64
 4   is_primary_item  40025 non-null  int64
 5   price_usd        40025 non-null  float64
 6   cogs_usd         40025 non-null  float64
dtypes: float64(2), int64(4), object(1)
memory usage: 2.1+ MB

### Changing datatype of created_at from object to datetime and of is_primary_item from int64 to boolean

In [108]:
oi["created_at"] = pd.to_datetime(oi["created_at"], dayfirst = True)
oi["is_primary_item"] = oi["is_primary_item"].astype("bool") 
oi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40025 entries, 0 to 40024
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    40025 non-null  int64
 1   created_at       40025 non-null  datetime64[ns]
 2   order_id         40025 non-null  int64
 3   product_id       40025 non-null  int64
 4   is_primary_item  40025 non-null  bool
 5   price_usd        40025 non-null  float64
 6   cogs_usd         40025 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(2), int64(3)
memory usage: 1.9 MB

In [109]:
oi.duplicated().sum()

np.int64(0)

In [110]:
oi.isnull().sum()

order_item_id      0
created_at         0
order_id           0
product_id         0
is_primary_item    0
price_usd          0
cogs_usd           0
dtype: int64

In [111]:
oi[["price_usd","cogs_usd"]].describe()

          price_usd      cogs_usd
count  40025.000000  40025.000000
mean      48.432473     18.047976
std        8.012370      3.856821
min       29.990000      9.490000
25%       49.990000     19.490000
50%       49.990000     19.490000
75%       49.990000     19.490000
max       59.990000     22.490000

### Adding year, month, month name columns

In [112]:
oi.insert(2,"year",oi["created_at"].dt.year)
oi.insert(3,"month",oi["created_at"].dt.month)
oi.insert(4,"month_name",oi["created_at"].dt.month_name())
oi

,order_item_id,created_at,year,month,month_name,order_id,product_id,is_primary_item,price_usd,cogs_usd
0,1,2012-03-19 10:42:00,2012,3,March,1,1,True,49.99,19.49
1,2,2012-03-19 19:27:00,2012,3,March,2,1,True,49.99,19.49
2,3,2012-03-20 06:44:00,2012,3,March,3,1,True,49.99,19.49
3,4,2012-03-20 09:41:00,2012,3,March,4,1,True,49.99,19.49
4,5,2012-03-20 11:28:00,2012,3,March,5,1,True,49.99,19.49
...,...,...,...,...,...,...,...,...,...,...
40020,40021,2015-03-19 04:10:00,2015,3,March,32310,4,True,29.99,9.49
40021,40022,2015-03-19 05:27:00,2015,3,March,32311,2,True,59.99,22.49
40022,40023,2015-03-19 05:27:00,2015,3,March,32311,4,False,29.99,9.49
40023,40024,2015-03-19 05:35:00,2015,3,March,32312,4,True,29.99,9.49
40024,40025,2015-03-19 05:38:00,2015,3,March,32313,1,True,49.99,19.49

### Exporting Dataset

In [113]:
oi.to_csv("order_items_cleaned.csv", index = False)

# 6. Order Item Refund

In [114]:
oir = pd.read_csv("D:/PROJECTS/Maven+Fuzzy+Factory(E-Commerce)/order_item_refunds.csv")
oir

,order_item_refund_id,created_at,order_item_id,order_id,refund_amount_usd
0,1,06-04-2012 11:32,57,57,49.99
1,2,13-04-2012 01:09,74,74,49.99
2,3,15-04-2012 07:03,71,71,49.99
3,4,17-04-2012 20:00,118,118,49.99
4,5,22-04-2012 20:53,116,116,49.99
...,...,...,...,...,...
1726,1727,30-03-2015 09:37,39950,32255,59.99
1727,1728,30-03-2015 21:33,39671,32049,49.99
1728,1729,31-03-2015 19:59,39729,32090,49.99
1729,1730,01-04-2015 03:54,39717,32079,59.99
1730,1731,01-04-2015 18:11,39947,32252,45.99

In [115]:
oir.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1731 entries, 0 to 1730
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_item_refund_id  1731 non-null   int64
 1   created_at            1731 non-null   object
 2   order_item_id         1731 non-null   int64
 3   order_id              1731 non-null   int64
 4   refund_amount_usd     1731 non-null   float64
dtypes: float64(1), int64(3), object(1)
memory usage: 67.7+ KB

### Changing datatype of created_at from object to datetime

In [116]:
oir["created_at"] = pd.to_datetime(oir["created_at"], dayfirst = True)
oir.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1731 entries, 0 to 1730
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_item_refund_id  1731 non-null   int64
 1   created_at            1731 non-null   datetime64[ns]
 2   order_item_id         1731 non-null   int64
 3   order_id              1731 non-null   int64
 4   refund_amount_usd     1731 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(3)
memory usage: 67.7 KB

In [117]:
oir.duplicated().sum()

np.int64(0)

In [118]:
oir.isnull().sum()

order_item_refund_id    0
created_at              0
order_item_id           0
order_id                0
refund_amount_usd       0
dtype: int64

### Adding year, month, month name columns

In [119]:
oir.insert(2,"year",oir["created_at"].dt.year)
oir.insert(3,"month",oir["created_at"].dt.month)
oir.insert(4,"month_name",oir["created_at"].dt.month_name())
oir

,order_item_refund_id,created_at,year,month,month_name,order_item_id,order_id,refund_amount_usd
0,1,2012-04-06 11:32:00,2012,4,April,57,57,49.99
1,2,2012-04-13 01:09:00,2012,4,April,74,74,49.99
2,3,2012-04-15 07:03:00,2012,4,April,71,71,49.99
3,4,2012-04-17 20:00:00,2012,4,April,118,118,49.99
4,5,2012-04-22 20:53:00,2012,4,April,116,116,49.99
...,...,...,...,...,...,...,...,...
1726,1727,2015-03-30 09:37:00,2015,3,March,39950,32255,59.99
1727,1728,2015-03-30 21:33:00,2015,3,March,39671,32049,49.99
1728,1729,2015-03-31 19:59:00,2015,3,March,39729,32090,49.99
1729,1730,2015-04-01 03:54:00,2015,4,April,39717,32079,59.99
1730,1731,2015-04-01 18:11:00,2015,4,April,39947,32252,45.99

### Exporting Dataset

In [120]:
oir.to_csv("order_item_refunds_cleaned.csv", index = False)